# Generated by Django 4.2.6 on 2023-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new friend request', 'New friend request'), ('new like', 'New like'), ('new comment', 'New comment')], max_length=100),
        ),
    ]
