# Generated by Django 4.2.6 on 2023-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', ' Accepted'), ('declined', 'Declined')], default='sent', max_length=15),
        ),
    ]
