# Generated by Django 4.2.6 on 2023-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_counter',
            field=models.IntegerField(default=0),
        ),
    ]
