# Generated by Django 4.2.6 on 2023-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_friends_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_counter',
            field=models.IntegerField(default=0),
        ),
    ]
