# Generated by Django 4.2.6 on 2023-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
