# Generated by Django 4.2.6 on 2023-10-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_posts_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posts_count',
        ),
    ]
