# Generated by Django 4.2.6 on 2023-10-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='occurences',
            new_name='occurence',
        ),
    ]
