# Generated by Django 4.2.6 on 2023-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_occurences_trend_occurence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='image',
            field=models.ImageField(upload_to='posts_attachments'),
        ),
    ]
