# Generated by Django 4.2.6 on 2023-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_postattachments_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='image',
            field=models.ImageField(upload_to='attachments_posts'),
        ),
    ]
